DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS comments(
	id SERIAL PRIMARY KEY,
	news INTEGER NOT NULL DEFAULT 0,
	parent INTEGER NOT NULL DEFAULT 0,
	content TEXT NOT NULL,
	pub_time BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),
	FOREIGN KEY (parent) REFERENCES comments(id) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO comments(id, content)
VALUES (0, 'Root comment');